services:

  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - bionicpro

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: localhost                                     # return http://localhost to the browser instead of http://keycloak
      KC_HOSTNAME_STRICT_BACK_CHANNEL: "false"                   # allow to use KC_HOSTNAME
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/keycloak-results-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      openldap:
        condition: service_started
    networks:
      - bionicpro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_REPORTS_URL: http://localhost:8001
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
    networks:
      - bionicpro

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      TOKEN_ENCRYPT_KEY: ${TOKEN_ENCRYPT_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: redis://redis:6379
      AUTH_HOST: localhost
      AUTH_PORT: 8000
    depends_on:
      - redis
    networks:
      - bionicpro

  reports:
    build:
      context: ./reports
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      REPORTS_PORT: 8001
      AUTH_HOST: auth
      AUTH_PORT: 8000
      OLAP_CONNECTION_STR: clickhouse://default:default@olap_db:8123/bionicpro
    depends_on:
      - auth
    networks:
      - bionicpro

  redis:
    image: redis:7-alpine
    restart: always
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD --maxmemory 256mb --maxmemory-policy allkeys-lru"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    networks:
      - bionicpro

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "bionicpro"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
    volumes:
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/01-users.ldif
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    command: --copy-service
    networks:
      - bionicpro

  telemetry_db:
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
      - --admin-token-file=/run/secrets/admin-token
    volumes:
      - telemetry_data:/var/lib/influxdb3
    secrets:
      - admin-token
    healthcheck:
      test: ["CMD-SHELL", "pgrep influxdb3 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - bionicpro

  olap_db:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./olap_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bionicpro
  
  crm_db:
    image: postgres:14
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - crm_pgdata:/var/lib/postgresql/data
      - ./crm_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - bionicpro

  airflow_db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_pass
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_user -d airflow"]
      interval: 5s
      retries: 5
    networks:
      - bionicpro

  airflow:
    image: apache/airflow:3.2.2-python3.11
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    command: standalone  
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@airflow_db:5432/airflow
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: True

      TM_DB_URL: http://telemetry_db:8181
      TM_DB_TOKEN_FILE: ./static_token.json
      TM_DB_DATA: ./data.csv
      CRM_CONNECTION_STR: "postgresql+asyncpg://crm_user:crm_password@crm_db:5432/crm_db"
      OLAP_CONNECTION_STR: "clickhouse://default:default@olap_db:8123/bionicpro"

    volumes:
      - ./telemetry_db/static_token.json:/opt/airflow/static_token.json:ro
      - ./telemetry_db/data.csv:/opt/airflow/data.csv:ro
      - ./data_pipeline/dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    depends_on:
      airflow_db:
        condition: service_healthy
      crm_db:
        condition: service_healthy
      telemetry_db:
        condition: service_healthy
      olap_db:
        condition: service_healthy
    networks:
      - bionicpro

volumes:
  pgdata:
  redisdata:
  ldap_data:
  ldap_config:
  telemetry_data:
  clickhouse_data:
  airflow_pgdata:
  crm_pgdata:

secrets:
  admin-token:
    file: ./telemetry_db/static_token.json

networks:
  bionicpro:
    name: bionicpro
    driver: bridge
